### ISSUE TITLE
Improvement to TER 

### ISSUE THREAD

**Issue by peterkraume** [j0nnybrav079/cbgooglemaps#3]
Please add the composer name `brinkert/cbgooglemaps` to the TER page https://extensions.typo3.org/extension/cbgooglemaps/. See here for details: https://insight.helhum.io/post/174851830180/improvements-to-composertypo3org

And while you're on it: please add the link to your GitHub repository to the TER page as well.

**Comment by j0nnybrav079** [comment]
hi Peter, unfortunately I am reading this issue one year later - sorry for that. The problem is, that this extension never was mine. I just forked it, because I needed it on packagist :)
